// Brand Colors
export const BRAND_COLORS = {
  red: "#DC2626",
  black: "#000000",
  white: "#FFFFFF",
  lightGray: "rgba(255, 255, 255, 0.60)",
} as const;

// Service Data Structure
export interface Service {
  slug: string;
  title: string;
  shortDescription: string;
  extendedDescription: string;
  keyFeatures: string[];
  benefits: string[];
  useCases: string[];
}

export const SERVICES: Service[] = [
  {
    slug: "mobile-development",
    title: "Mobile Development",
    shortDescription: "Native and cross-platform mobile applications built for iOS and Android.",
    extendedDescription: "We develop high-performance mobile applications that deliver exceptional user experiences across iOS and Android platforms. Our mobile solutions are built with modern frameworks, ensuring native performance while maximizing code reusability for faster time-to-market.",
    keyFeatures: [
      "Native iOS and Android development",
      "Cross-platform solutions with React Native and Flutter",
      "Custom UI/UX design implementation",
      "App Store and Play Store optimization",
      "Push notifications and real-time updates",
      "Offline functionality and data synchronization",
      "Performance optimization and testing",
      "Post-launch support and maintenance",
    ],
    benefits: [
      "Reach customers on their preferred devices",
      "Improved customer engagement and retention",
      "Enhanced brand presence in mobile ecosystem",
      "Streamlined business processes through mobile workflows",
      "Real-time data access and synchronization",
      "Increased revenue through mobile commerce capabilities",
    ],
    useCases: [
      "Customer-facing mobile apps for e-commerce and services",
      "Internal employee tools and productivity apps",
      "Field service management applications",
      "Real-time collaboration and communication platforms",
      "Mobile-first SaaS solutions",
      "Healthcare patient portals and telemedicine apps",
    ],
  },
  {
    slug: "web-development",
    title: "Web Development",
    shortDescription: "Modern, responsive web applications using the latest technologies.",
    extendedDescription: "We create responsive, scalable web applications that perform flawlessly across all devices and browsers. Our web solutions leverage cutting-edge technologies to deliver fast, secure, and maintainable code that grows with your business.",
    keyFeatures: [
      "Responsive design for all screen sizes",
      "Modern frameworks: React, Next.js, Vue.js",
      "Server-side rendering for optimal performance",
      "SEO optimization and accessibility compliance",
      "Progressive Web App (PWA) capabilities",
      "API integration and third-party services",
      "Content management system integration",
      "Performance monitoring and analytics",
    ],
    benefits: [
      "Wide accessibility across all devices",
      "Improved search engine visibility",
      "Faster page loads and better user experience",
      "Scalable architecture for business growth",
      "Easy content management and updates",
      "Enhanced security with modern best practices",
    ],
    useCases: [
      "Corporate websites and landing pages",
      "E-commerce platforms and online stores",
      "Business dashboards and admin panels",
      "Customer portals and self-service platforms",
      "Marketing and campaign websites",
      "Educational platforms and learning management systems",
    ],
  },
  {
    slug: "email-client-development",
    title: "Email Client Development",
    shortDescription: "Custom email solutions tailored to your business needs.",
    extendedDescription: "We build custom email client applications that integrate seamlessly with your business workflows. Our email solutions provide advanced features, improved security, and enhanced productivity for teams that rely on email communication.",
    keyFeatures: [
      "Custom email client interfaces",
      "Multiple email account management",
      "Advanced search and filtering capabilities",
      "Email templates and automation",
      "Calendar and scheduling integration",
      "Security and encryption features",
      "API integration with email providers",
      "Custom branding and white-label options",
    ],
    benefits: [
      "Streamlined email communication workflows",
      "Improved productivity with advanced features",
      "Enhanced security and data protection",
      "Customized experience tailored to your needs",
      "Better organization and email management",
      "Reduced reliance on third-party email providers",
    ],
    useCases: [
      "Enterprise email client solutions",
      "Industry-specific email management tools",
      "Integrated email within business applications",
      "Secure email clients for sensitive communications",
      "Multi-account email management platforms",
      "Custom email automation and workflows",
    ],
  },
  {
    slug: "enterprise-systems",
    title: "Enterprise Systems",
    shortDescription: "Scalable enterprise software solutions for complex business requirements.",
    extendedDescription: "We design and develop enterprise-grade software systems that handle complex business logic, large-scale data processing, and mission-critical operations. Our enterprise solutions are built for reliability, scalability, and long-term maintainability.",
    keyFeatures: [
      "Microservices and distributed architecture",
      "Scalable cloud infrastructure",
      "Database design and optimization",
      "API development and integration",
      "Security and compliance features",
      "Real-time data processing",
      "Workflow automation and business logic",
      "Legacy system integration and migration",
    ],
    benefits: [
      "Handles complex business requirements at scale",
      "Improved operational efficiency",
      "Data-driven decision making capabilities",
      "Reduced operational costs through automation",
      "Enhanced security and compliance",
      "Future-proof architecture that scales with growth",
    ],
    useCases: [
      "Enterprise resource planning (ERP) systems",
      "Customer relationship management (CRM) platforms",
      "Supply chain and inventory management",
      "Financial management and accounting systems",
      "Human resources and talent management",
      "Document management and workflow systems",
    ],
  },
  {
    slug: "ai-enhancement-ai-workflows",
    title: "AI Enhancement / AI Workflows",
    shortDescription: "Intelligent automation and AI-powered workflows to streamline operations.",
    extendedDescription: "We integrate artificial intelligence and machine learning capabilities into your existing systems to automate processes, extract insights, and enhance decision-making. Our AI solutions are practical, scalable, and designed to deliver immediate value.",
    keyFeatures: [
      "Custom AI model development and integration",
      "Natural language processing and chatbots",
      "Computer vision and image recognition",
      "Predictive analytics and machine learning",
      "Workflow automation with AI decision-making",
      "Data analysis and insight generation",
      "AI-powered search and recommendation systems",
      "Integration with existing business systems",
    ],
    benefits: [
      "Automated repetitive tasks and processes",
      "Data-driven insights for better decision making",
      "Improved customer service through AI assistants",
      "Enhanced accuracy and reduced human error",
      "24/7 intelligent automation capabilities",
      "Competitive advantage through AI adoption",
    ],
    useCases: [
      "Intelligent document processing and extraction",
      "AI-powered customer support chatbots",
      "Predictive maintenance and analytics",
      "Content moderation and classification",
      "Personalized recommendations and marketing",
      "Automated data entry and validation",
    ],
  },
  {
    slug: "web-applications",
    title: "Web Applications",
    shortDescription: "Full-stack web applications with robust architecture and performance.",
    extendedDescription: "We build comprehensive full-stack web applications from the ground up, combining powerful backend systems with intuitive frontend interfaces. Our web applications are designed for performance, security, and exceptional user experiences.",
    keyFeatures: [
      "Full-stack development (frontend and backend)",
      "RESTful and GraphQL API design",
      "Database design and optimization",
      "User authentication and authorization",
      "Real-time features with WebSockets",
      "File upload and media management",
      "Third-party integrations and APIs",
      "Comprehensive testing and quality assurance",
    ],
    benefits: [
      "Complete solution from database to user interface",
      "Consistent user experience across platforms",
      "Centralized data management",
      "Easy updates and feature additions",
      "Cost-effective development and maintenance",
      "Unified brand experience",
    ],
    useCases: [
      "SaaS platforms and subscription services",
      "Project management and collaboration tools",
      "Customer relationship management systems",
      "Online marketplaces and booking platforms",
      "Content management and publishing systems",
      "Business intelligence and analytics dashboards",
    ],
  },
  {
    slug: "integrations-and-automation",
    title: "Integrations and Automation",
    shortDescription: "Seamless integrations and automated workflows to connect your systems.",
    extendedDescription: "We connect your disparate systems and automate workflows to eliminate manual processes and improve efficiency. Our integration solutions enable seamless data flow between applications, reducing errors and saving valuable time.",
    keyFeatures: [
      "API integration and development",
      "Data synchronization between systems",
      "Workflow automation and orchestration",
      "Webhook implementation and management",
      "Legacy system integration",
      "ETL (Extract, Transform, Load) processes",
      "Real-time data pipelines",
      "Integration monitoring and error handling",
    ],
    benefits: [
      "Eliminated manual data entry and processes",
      "Reduced errors and improved data accuracy",
      "Time savings through automation",
      "Better visibility across systems",
      "Improved operational efficiency",
      "Seamless user experience across platforms",
    ],
    useCases: [
      "Connecting CRM with marketing automation tools",
      "E-commerce platform integrations",
      "Accounting and payment system connections",
      "Inventory and shipping system automation",
      "HR and payroll system integrations",
      "Customer support tool integrations",
    ],
  },
];

