// Brand Colors
export const BRAND_COLORS = {
  red: "#DC2626",
  redMuted: "#B91C1C",
  black: "#000000",
  white: "#FFFFFF",
  lightGray: "rgba(255, 255, 255, 0.60)",
} as const;

// Service Data Structure
export interface Service {
  slug: string;
  title: string;
  shortDescription: string;
  extendedDescription: string;
  keyFeatures: string[];
  benefits: string[];
  useCases: string[];
}

export const SERVICES: Service[] = [
  {
    slug: "mobile-development",
    title: "Mobile Development",
    shortDescription: "Native and cross-platform mobile applications engineered for performance and reliability.",
    extendedDescription: "We develop high-performance mobile applications that deliver refined user experiences across iOS and Android platforms. Our mobile solutions are architected with modern frameworks, ensuring native performance while maintaining code quality that scales with your business.",
    keyFeatures: [
      "Native iOS and Android development",
      "Cross-platform solutions with React Native and Flutter",
      "Precision UI/UX implementation",
      "App Store and Play Store optimization",
      "Push notifications and real-time updates",
      "Offline functionality and data synchronization",
      "Performance optimization and load testing",
      "Ongoing maintenance and strategic support",
    ],
    benefits: [
      "Reach customers on their preferred devices",
      "Enhanced engagement through refined mobile experiences",
      "Strengthened brand presence in mobile ecosystem",
      "Streamlined operations through mobile workflows",
      "Real-time data access and synchronization",
      "Increased revenue through mobile commerce capabilities",
    ],
    useCases: [
      "Customer-facing mobile platforms",
      "Internal productivity and operations tools",
      "Field service management applications",
      "Real-time collaboration platforms",
      "Mobile-first SaaS solutions",
      "Healthcare and telemedicine portals",
    ],
  },
  {
    slug: "web-development",
    title: "Web Development",
    shortDescription: "Modern, responsive web experiences built with meticulous attention to craft.",
    extendedDescription: "We create responsive, scalable web applications that perform flawlessly across all devices and browsers. Our web solutions leverage proven technologies to deliver fast, secure, and maintainable systems that grow with your business.",
    keyFeatures: [
      "Responsive design for every viewport",
      "Modern frameworks: React, Next.js, Vue.js",
      "Server-side rendering for optimal performance",
      "SEO optimization and accessibility compliance",
      "Progressive Web App (PWA) capabilities",
      "API integration and third-party services",
      "Content management system integration",
      "Performance monitoring and analytics",
    ],
    benefits: [
      "Broad accessibility across all devices",
      "Improved search engine visibility",
      "Faster page loads and refined user experience",
      "Scalable architecture designed for growth",
      "Intuitive content management",
      "Enterprise-grade security practices",
    ],
    useCases: [
      "Corporate websites and digital presence",
      "E-commerce platforms and online stores",
      "Business intelligence dashboards",
      "Customer portals and self-service platforms",
      "Campaign and marketing websites",
      "Educational platforms and learning systems",
    ],
  },
  {
    slug: "email-client-development",
    title: "Email Client Development",
    shortDescription: "Custom email solutions architected for your business workflows.",
    extendedDescription: "We build custom email client applications that integrate seamlessly with your business operations. Our email solutions provide advanced features, enhanced security, and improved productivity for teams that depend on reliable communication.",
    keyFeatures: [
      "Custom email client interfaces",
      "Multi-account management",
      "Advanced search and filtering",
      "Email templates and automation",
      "Calendar and scheduling integration",
      "Security and encryption features",
      "API integration with email providers",
      "Custom branding and white-label options",
    ],
    benefits: [
      "Streamlined communication workflows",
      "Improved productivity with advanced features",
      "Enhanced security and data protection",
      "Tailored experience for your organization",
      "Better organization and email management",
      "Reduced dependency on third-party providers",
    ],
    useCases: [
      "Enterprise email client solutions",
      "Industry-specific email management",
      "Integrated email within business applications",
      "Secure email for sensitive communications",
      "Multi-account management platforms",
      "Automated email workflows",
    ],
  },
  {
    slug: "enterprise-systems",
    title: "Enterprise Systems",
    shortDescription: "Mission-critical enterprise software engineered for reliability at scale.",
    extendedDescription: "We architect and develop enterprise-grade software systems that handle complex business logic, large-scale data processing, and mission-critical operations. Our solutions are built for reliability, scalability, and long-term maintainability.",
    keyFeatures: [
      "Microservices and distributed architecture",
      "Scalable cloud infrastructure",
      "Database design and optimization",
      "API development and integration",
      "Security and compliance features",
      "Real-time data processing",
      "Workflow automation and business logic",
      "Legacy system integration and migration",
    ],
    benefits: [
      "Handles complex requirements at enterprise scale",
      "Improved operational efficiency",
      "Data-driven decision making capabilities",
      "Reduced operational costs through automation",
      "Enhanced security and regulatory compliance",
      "Future-proof architecture that scales with growth",
    ],
    useCases: [
      "Enterprise resource planning (ERP) systems",
      "Customer relationship management (CRM) platforms",
      "Supply chain and inventory management",
      "Financial management and accounting systems",
      "Human resources and talent management",
      "Document management and workflow systems",
    ],
  },
  {
    slug: "ai-enhancement-ai-workflows",
    title: "AI Systems & Workflows",
    shortDescription: "Intelligent systems that enhance decision-making and automate complex processes.",
    extendedDescription: "We integrate artificial intelligence and machine learning capabilities into your existing systems to automate processes, extract insights, and enhance decision-making. Our AI solutions are practical, scalable, and architected to deliver measurable value.",
    keyFeatures: [
      "Custom AI model development and integration",
      "Natural language processing and conversational AI",
      "Computer vision and image recognition",
      "Predictive analytics and machine learning",
      "Workflow automation with AI decision-making",
      "Data analysis and insight generation",
      "AI-powered search and recommendation systems",
      "Integration with existing business systems",
    ],
    benefits: [
      "Automated complex processes at scale",
      "Data-driven insights for strategic decisions",
      "Enhanced customer experience through intelligent systems",
      "Improved accuracy and reduced human error",
      "Continuous intelligent automation",
      "Competitive advantage through AI adoption",
    ],
    useCases: [
      "Intelligent document processing and extraction",
      "AI-powered customer support systems",
      "Predictive maintenance and analytics",
      "Content moderation and classification",
      "Personalized recommendations",
      "Automated data validation and enrichment",
    ],
  },
  {
    slug: "web-applications",
    title: "Web Applications",
    shortDescription: "Full-stack web applications with robust architecture and exceptional performance.",
    extendedDescription: "We build comprehensive full-stack web applications from the ground up, combining powerful backend systems with intuitive frontend interfaces. Our applications are engineered for performance, security, and refined user experiences.",
    keyFeatures: [
      "Full-stack development (frontend and backend)",
      "RESTful and GraphQL API design",
      "Database architecture and optimization",
      "User authentication and authorization",
      "Real-time features with WebSockets",
      "File management and media handling",
      "Third-party integrations and APIs",
      "Comprehensive testing and quality assurance",
    ],
    benefits: [
      "Complete solution from database to interface",
      "Consistent experience across platforms",
      "Centralized data management",
      "Seamless updates and feature additions",
      "Cost-effective development and maintenance",
      "Unified brand experience",
    ],
    useCases: [
      "SaaS platforms and subscription services",
      "Project management and collaboration tools",
      "Customer relationship management systems",
      "Online marketplaces and booking platforms",
      "Content management and publishing systems",
      "Business intelligence and analytics dashboards",
    ],
  },
  {
    slug: "integrations-and-automation",
    title: "Integrations & Automation",
    shortDescription: "Seamless system connections and automated workflows for operational efficiency.",
    extendedDescription: "We connect your disparate systems and automate workflows to eliminate manual processes and improve efficiency. Our integration solutions enable seamless data flow between applications, reducing errors and reclaiming valuable time.",
    keyFeatures: [
      "API integration and development",
      "Data synchronization between systems",
      "Workflow automation and orchestration",
      "Webhook implementation and management",
      "Legacy system integration",
      "ETL (Extract, Transform, Load) processes",
      "Real-time data pipelines",
      "Integration monitoring and error handling",
    ],
    benefits: [
      "Eliminated manual data entry and processes",
      "Reduced errors and improved data accuracy",
      "Significant time savings through automation",
      "Better visibility across systems",
      "Improved operational efficiency",
      "Seamless experience across platforms",
    ],
    useCases: [
      "CRM and marketing automation integration",
      "E-commerce platform connections",
      "Accounting and payment system integration",
      "Inventory and shipping automation",
      "HR and payroll system connections",
      "Customer support tool integrations",
    ],
  },
];
